#!/bin/bash

set -euo pipefail

root=$(cd -P -- "$(dirname -- "$0")/.." && pwd)
helper="$root/scripts/herdr-config"
# A named-session fixture needs Unix-domain sockets below this directory.
# macOS's per-user TMPDIR can exceed the socket-path limit once the simulated
# Herdr config hierarchy is appended, so keep this test-only root short.
test_root=$(mktemp -d /tmp/agentstart-herdr-config.XXXXXX)
trap 'rm -rf "$test_root"' EXIT

fail() {
    printf 'herdr-config test: %s\n' "$*" >&2
    exit 1
}

test_home="$test_root/home"
test_bin="$test_root/bin"
test_log="$test_root/herdr.log"
test_active="$test_root/check-active"
base_config="$test_root/base-config.toml"
invalid_config="$test_root/base-invalid.toml"
config_target="$test_home/.config/herdr/config.toml"
managed_marker="# Generated by AgentStart's herdr-config. Do not edit."
legacy_marker="# Generated by AgentStart's herdr-tinty. Do not edit."

mkdir -p "$test_home" "$test_bin" "$(dirname -- "$config_target")"

cat >"$base_config" <<'EOF'
[keys]
prefix = "ctrl+space"

[theme]
name = "terminal"
auto_switch = false
EOF

{
    cat "$base_config"
    printf 'INVALID\n'
} >"$invalid_config"

cat >"$test_bin/herdr" <<'EOF'
#!/bin/bash
set -euo pipefail

session_name=default
if [ "${1:-}" = --session ]; then
    session_name="${2:?missing Herdr session name}"
    shift 2
fi

case "${1:-}:${2:-}" in
    config:check)
        printf 'check %s\n' "${HERDR_CONFIG_PATH:?}" >>"${TEST_HERDR_LOG:?}"
        if grep -F INVALID "$HERDR_CONFIG_PATH" >/dev/null; then
            printf 'invalid fixture config\n' >&2
            exit 1
        fi
        if [ "${TEST_HERDR_CHECK_DELAY:-0}" = 1 ]; then
            active_owned=0
            if mkdir "${TEST_HERDR_ACTIVE:?}" 2>/dev/null; then
                active_owned=1
            else
                printf 'overlap\n' >>"$TEST_HERDR_LOG"
            fi
            sleep 0.1
            if [ "$active_owned" -eq 1 ]; then
                rmdir "$TEST_HERDR_ACTIVE"
            fi
        fi
        ;;
    server:reload-config)
        printf 'reload %s\n' "$session_name" >>"${TEST_HERDR_LOG:?}"
        if [ "${TEST_HERDR_RELOAD_FAIL:-0}" = 1 ]; then
            printf 'server is not running\n' >&2
            exit 1
        fi
        if [ "${TEST_HERDR_RELOAD_PARTIAL:-0}" = 1 ]; then
            printf '%s\n' '{"id":"fixture:reload","result":{"diagnostics":["unknown config key ui.sidebar_max_width; ignoring key"],"status":"partial","type":"config_reload"}}'
        fi
        ;;
    *)
        printf 'unexpected herdr fixture invocation: %s\n' "$*" >&2
        exit 2
        ;;
esac
EOF
chmod +x "$test_bin/herdr"

export HOME="$test_home"
export AGENTSTART_HERDR_CONFIG_SOURCE="$base_config"
export AGENTSTART_HERDR_CONFIG_TARGET="$config_target"
export AGENTSTART_HERDR_LOCK_DIR="$test_home/.local/state/agentstart/herdr-config.lock"
export AGENTSTART_HERDR_BIN="$test_bin/herdr"
export TEST_HERDR_LOG="$test_log"
export TEST_HERDR_ACTIVE="$test_active"

# Installation renders the tracked base into a marked, validated live file.
"$helper" install >/dev/null
[ -f "$config_target" ] && [ ! -L "$config_target" ] \
    || fail "install did not render a live Herdr config file"
grep -Fqx "$managed_marker" "$config_target" \
    || fail "generated Herdr config is missing its ownership marker"
grep -Fqx 'prefix = "ctrl+space"' "$config_target" \
    || fail "generated Herdr config does not carry the tracked base"
grep -Fqx 'name = "terminal"' "$config_target" \
    || fail "generated Herdr config does not keep the terminal theme"

# A config render reloads the default server and every live named session.
# Bind then close Unix sockets: the fixture only needs a socket path for the
# renderer to discover, while the fake Herdr CLI records the reload target.
session_root="$(dirname -- "$config_target")/sessions"
mkdir -p "$session_root/jobs" "$session_root/review"
python3 - "$session_root/jobs/herdr.sock" "$session_root/review/herdr.sock" <<'PY'
import socket
import sys

for path in sys.argv[1:]:
    sock = socket.socket(socket.AF_UNIX)
    sock.bind(path)
    sock.close()
PY
: >"$test_log"
"$helper" install >/dev/null
grep -Fqx 'reload default' "$test_log" \
    || fail "default Herdr server was not reloaded"
grep -Fqx 'reload jobs' "$test_log" \
    || fail "jobs Herdr session was not reloaded"
grep -Fqx 'reload review' "$test_log" \
    || fail "review Herdr session was not reloaded"

# The render carries no palette: a color is the one thing it must never add.
if grep -Eq '^\[theme\.custom\]' "$config_target"; then
    fail "generated Herdr config still carries a custom palette"
fi
if grep -Eq '#[0-9a-fA-F]{6}\b' "$config_target"; then
    fail "generated Herdr config contains a hardcoded hex color"
fi

# A file left by the retired herdr-tinty render is ours to replace.
printf '%s\nstale = true\n' "$legacy_marker" >"$config_target"
"$helper" install >/dev/null
grep -Fqx "$managed_marker" "$config_target" \
    || fail "a config left by the retired herdr-tinty render was not migrated"

# A rejected candidate must leave the live config byte-for-byte unchanged.
cp "$config_target" "$test_root/config-before-invalid"
if AGENTSTART_HERDR_CONFIG_SOURCE="$invalid_config" "$helper" install \
    >/dev/null 2>&1; then
    fail "an invalid Herdr candidate was accepted"
fi
cmp -s "$test_root/config-before-invalid" "$config_target" \
    || fail "invalid candidate changed the live Herdr config"

# Independent files and links are never treated as ours.
independent_target="$test_root/independent/config.toml"
mkdir -p "$(dirname -- "$independent_target")"
printf 'keep me\n' >"$independent_target"
if AGENTSTART_HERDR_CONFIG_TARGET="$independent_target" "$helper" install \
    >/dev/null 2>&1; then
    fail "an independent regular Herdr config was replaced"
fi
[ "$(cat "$independent_target")" = 'keep me' ] \
    || fail "independent regular Herdr config changed"

unrelated_source="$test_root/unrelated-source.toml"
unrelated_target="$test_root/unrelated/config.toml"
mkdir -p "$(dirname -- "$unrelated_target")"
printf 'keep this link\n' >"$unrelated_source"
ln -s "$unrelated_source" "$unrelated_target"
if AGENTSTART_HERDR_CONFIG_TARGET="$unrelated_target" "$helper" install \
    >/dev/null 2>&1; then
    fail "a linked Herdr config was replaced"
fi
[ -L "$unrelated_target" ] \
    || fail "linked Herdr config changed"

# Rendering remains successful when no server is available; the next Herdr
# start will read the already-validated file.
TEST_HERDR_RELOAD_FAIL=1 "$helper" install >/dev/null 2>&1 \
    || fail "a missing Herdr server made a valid render fail"

# A running server can be older than the installed binary and accept only part
# of a config that `herdr config check` validates. Keep the render successful,
# but surface the server diagnostic instead of silently discarding it.
partial_stderr="$test_root/reload-partial.stderr"
TEST_HERDR_RELOAD_PARTIAL=1 "$helper" install >/dev/null 2>"$partial_stderr" \
    || fail "a partial Herdr reload made a valid render fail"
grep -F 'default server reload was partial' "$partial_stderr" >/dev/null \
    || fail "partial Herdr reload status was hidden"
grep -F 'unknown config key ui.sidebar_max_width' "$partial_stderr" >/dev/null \
    || fail "partial Herdr reload diagnostic was hidden"

# The theme manager is gone: no command survives that would reapply a palette.
for command in apply-theme render-config next previous; do
    if "$helper" "$command" >/dev/null 2>&1; then
        fail "$command is still accepted after the theme manager was removed"
    fi
done

# Two concurrent renders serialize their validation sections.
: >"$test_log"
TEST_HERDR_CHECK_DELAY=1 "$helper" install >/dev/null &
first_pid=$!
TEST_HERDR_CHECK_DELAY=1 "$helper" install >/dev/null &
second_pid=$!
wait "$first_pid"
wait "$second_pid"
if grep -F overlap "$test_log" >/dev/null; then
    fail "concurrent config renders were not serialized"
fi

printf 'herdr-config tests passed\n'
